import { StyleSheet } from 'react-native';

export const createStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
    },
    title: {
      fontFamily: 'Switzer-Semibold',
      fontSize: 26,
      color: '#111827',
      marginBottom: 6,
    },
    subtitle: {
      fontFamily: 'Switzer-Regular',
      fontSize: 15,
      lineHeight: 22,
      color: '#111827',
      marginBottom: 20,
    },
    guideArea: {
      width: '100%',
      alignItems: 'center',
      marginTop: 4,
    },
    guideCircle: {
      width: '100%',
      aspectRatio: 1,
      borderRadius: 999,
      borderWidth: 5,
      borderColor: '#3B82F6',
      backgroundColor: '#111827',
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
    },
    cameraPreview: {
      width: '100%',
      height: '100%',
    },
    cameraFallback: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#111827',
    },
    permissionButton: {
      backgroundColor: '#2563EB',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    permissionButtonText: {
      color: '#FFFFFF',
      fontFamily: 'Switzer-Semibold',
      fontSize: 14,
    },
    permissionHint: {
      color: '#D1D5DB',
      fontFamily: 'Switzer-Regular',
      fontSize: 12,
      marginTop: 10,
    },
    guideOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      paddingHorizontal: 26,
      paddingTop: 20,
    },
    guideSvg: {
      width: '100%',
      height: '100%',
    },
    checklistWrap: {
      marginTop: 18,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
      rowGap: 12,
    },
    checklistPill: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#D1D5DB',
      borderRadius: 18,
      paddingVertical: 8,
      paddingHorizontal: 14,
      backgroundColor: '#FFFFFF',
    },
    checklistText: {
      fontFamily: 'Switzer-Medium',
      fontSize: 14,
      color: '#111827',
      marginLeft: 8,
    },
    previewContainer: {
      width: '100%',
      marginTop: 4,
      padding: 16,
    },
    previewImage: {
      width: '100%',
      aspectRatio: 0.74,
      borderRadius: 8,
      backgroundColor: '#F3F4F6',
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 0.3,
      borderTopColor: '#E5E7EB',
    },
    buttonSecondaryFooter: {
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#D1D5DB',
      borderRadius: 24,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 12,
    },
    buttonSecondaryText: {
      fontFamily: 'Switzer-Medium',
      fontSize: 16,
      color: '#111827',
    },
    buttonPrimary: {
      backgroundColor: '#3981FF',
      borderRadius: 24,
      paddingVertical: 14,
      alignItems: 'center',
    },
    buttonText: {
      fontFamily: 'Switzer-Medium',
      fontSize: 16,
      color: '#FFFFFF',
    },
  });
