import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.45)',
    zIndex: 99999,
  },
  sheetContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingTop: 24,
    paddingHorizontal: 20,
    paddingBottom: 28,
    width: '100%',
  },
  softSheetContainer: {
    width: '90%',
    borderRadius: 16,
    paddingTop: 18,
    paddingBottom: 14,
    marginBottom: 300,
  },
  softHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  bellIcon: {
    width: 30,
    height: 30,
    marginRight: 10,
  },
  title: {
    fontSize: 24,
    lineHeight: 32,
    color: '#000000',
    fontFamily: 'Switzer-Semibold',
    marginBottom: 16,
  },
  softTitle: {
    flex: 1,
    fontSize: 24,
    lineHeight: 36,
    marginBottom: 0,
  },
  description: {
    fontSize: 16,
    lineHeight: 22,
    color: '#000000',
    fontFamily: 'Switzer-Regular',
  },
  bulletListContainer: {
    gap: 2,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  bulletPrefix: {
    color: '#000000',
    fontSize: 14,
    lineHeight: 20,
    marginRight: 6,
    fontFamily: 'Switzer-Medium',
  },
  bulletText: {
    flex: 1,
    color: '#000000',
    fontSize: 16,
    lineHeight: 20,
    fontFamily: 'Switzer-Regular',
  },
  updateButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 999,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 24,
  },
  softUpdateButton: {
    height: 45,
  },
  updateButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    lineHeight: 20,
    fontFamily: 'Switzer-Medium',
  },
  laterButton: {
    marginTop: 10,
    borderRadius: 999,
    height: 45,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#FFFFFF',
  },
  laterButtonText: {
    color: '#000000',
    fontSize: 14,
    lineHeight: 20,
    fontFamily: 'Switzer-Medium',
  },
});
