import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  content: {
    paddingBottom: 40,
  },
  curveCutout: {
    position: 'absolute',
    width: width * 2.43,
    height: width * 2.25,
    borderRadius: (width * 2.43) / 2,
    bottom: -width * 2.13,
    backgroundColor: '#FFFFFF',
  },
  resultCard: {
    backgroundColor: '#3B82F6',
    alignItems: 'center',
    paddingTop: 60,
    paddingBottom: 70,
    position: 'relative',
    overflow: 'hidden',
  },
  resultIcon: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  resultTitle: {
    fontFamily: 'Switzer-Regular',
    fontSize: 16,
    color: '#FFFFFF',
    marginBottom: 8,
  },
  resultAmount: {
    fontFamily: 'Switzer-Bold',
    fontSize: 48,
    color: '#FFFFFF',
    zIndex: 1,
  },
  recipientBox: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 24,
    borderRadius: 8,
    padding: 16,
    marginTop: -55,
    zIndex: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  recipientLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  bankLogoWrapper: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginRight: 14,
  },
  bankText: {
    fontSize: 12,
    fontFamily: 'Switzer-Bold',
    color: '#005E9F',
  },
  recipientInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  recipientName: {
    fontFamily: 'Switzer-Bold',
    fontSize: 16,
    color: '#111827',
    marginBottom: 2,
  },
  recipientMethod: {
    fontFamily: 'Switzer-Regular',
    fontSize: 13,
    color: '#6B7280',
  },
  detailsCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 40,
  },
  sectionTitle: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    color: '#111827',
    marginBottom: 16,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    width: '100%',
  },
  detailLabel: {
    fontFamily: 'Switzer-Regular',
    fontSize: 14,
    color: '#6B7280',
    flex: 1,
    width: '50%',
    flexShrink: 0,
    includeFontPadding: false,
  },
  detailValue: {
    fontFamily: 'Switzer-Medium',
    fontSize: 14,
    color: '#111827',
    textAlign: 'right',
    flex: 1,
    width: '50%',
    flexShrink: 1,

    flexWrap: 'wrap',
  },
  footerContainer: {
    backgroundColor: '#FFFFFF',
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 34 : 24,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 8,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#D4D4D4',
    borderRadius: 40,
    paddingVertical: 14,
    backgroundColor: '#FFFFFF',
  },
  actionText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 14,
    color: '#111827',
  },
  homeButton: {
    backgroundColor: '#3B82F6',
    borderRadius: 40,
    paddingVertical: 16,
    marginHorizontal: 24,
    alignItems: 'center',
    marginTop: 10,
  },
  homeButtonText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 16,
    color: '#FFFFFF',
  },
});
