import { StyleSheet } from 'react-native';

export const createStyles = () =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FFFFFF',
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
    },
    title: {
      fontFamily: 'Switzer-Semibold',
      fontSize: 26,
      color: '#111827',
      marginBottom: 6,
    },
    subtitle: {
      fontFamily: 'Switzer-Regular',
      fontSize: 15,
      lineHeight: 22,
      color: '#4B5563',
      marginBottom: 18,
    },
    frameWrap: {
      borderRadius: 8,
      minHeight: 420,
      justifyContent: 'center',
      alignItems: 'center',
    },
    frame: {
      width: '100%',
      aspectRatio: 0.74,
      borderRadius: 8,
      overflow: 'hidden',
      backgroundColor: '#111827',
      justifyContent: 'center',
      alignItems: 'center',
    },
    guidanceOverlay: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 18,
      paddingTop: 80,
      paddingBottom: 40,
    },
    guidanceFrame: {
      width: '100%',
      aspectRatio: 1.58,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      borderRadius: 4,
      backgroundColor: 'transparent',
      padding: 8,
    },
    guidanceInnerRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'stretch',
    },
    guidanceInnerLeftBox: {
      flex: 1,
      marginTop: 16,
      height: '80%',
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      borderRadius: 4,
      backgroundColor: 'transparent',
      marginRight: 8,
    },
    guidanceInnerRightBox: {
      width: '31%',
      height: '70%',
      marginTop: 16,
      borderWidth: 1.5,
      borderColor: '#FFFFFF',
      borderRadius: 4,
      backgroundColor: 'transparent',
    },
    guidanceInfo: {
      alignItems: 'center',
      paddingHorizontal: 16,
    },
    guidanceInfoIconBox: {
      width: 62,
      height: 42,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: '#FFFFFF',
      justifyContent: 'center',
      marginBottom: 14,
      padding: 4,
    },
    guidanceInfoTitle: {
      color: '#FFFFFF',
      fontFamily: 'Switzer-Semibold',
      fontSize: 18,
      textAlign: 'center',
      marginBottom: 8,
    },
    guidanceInfoSubtitle: {
      color: '#E5E7EB',
      fontFamily: 'Switzer-Regular',
      fontSize: 14,
      lineHeight: 21,
      textAlign: 'center',
    },
    guidanceInfoIconLine: {
      position: 'absolute',
      top: 12,
      left: 36,
      right: 0,
      bottom: 0,
    },
    guidanceInfoIconLineStrip: {
      width: 12,
      height: 2,
      backgroundColor: '#FFFFFF',
      borderRadius: 1,
    },
    cameraPreview: {
      width: '100%',
      height: '100%',
    },
    frameImage: {
      width: '100%',
      height: '100%',
    },
    framePlaceholder: {
      flex: 1,
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 24,
      gap: 10,
      position: 'relative',
    },
    placeholderIconBox: {
      width: 52,
      height: 52,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFFFFF',
      marginBottom: 4,
    },
    placeholderTitle: {
      color: '#FFFFFF',
      fontFamily: 'Switzer-Semibold',
      fontSize: 18,
      textAlign: 'center',
    },
    placeholderSubtitle: {
      color: '#E5E7EB',
      fontFamily: 'Switzer-Regular',
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
    },
    permissionButton: {
      backgroundColor: '#2563EB',
      borderRadius: 20,
      paddingHorizontal: 16,
      paddingVertical: 10,
      marginTop: 6,
    },
    permissionButtonText: {
      color: '#FFFFFF',
      fontFamily: 'Switzer-Semibold',
      fontSize: 14,
    },
    permissionHint: {
      color: '#D1D5DB',
      fontFamily: 'Switzer-Regular',
      fontSize: 12,
      marginTop: 4,
    },
    footer: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      backgroundColor: '#FFFFFF',
      borderTopWidth: 0.3,
      borderTopColor: '#E5E7EB',
    },
    buttonPrimary: {
      backgroundColor: '#3981FF',
      borderRadius: 24,
      paddingVertical: 14,
      alignItems: 'center',
    },
    buttonSecondary: {
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#D1D5DB',
      borderRadius: 24,
      paddingVertical: 14,
      alignItems: 'center',
      marginTop: 12,
      marginBottom: 6,
    },
    buttonSecondaryFooter: {
      backgroundColor: '#FFFFFF',
      borderWidth: 1,
      borderColor: '#D1D5DB',
      borderRadius: 24,
      paddingVertical: 14,
      alignItems: 'center',
      marginBottom: 12,
    },
    buttonText: {
      fontFamily: 'Switzer-Medium',
      fontSize: 16,
      color: '#FFFFFF',
    },
    buttonSecondaryText: {
      fontFamily: 'Switzer-Medium',
      fontSize: 16,
      color: '#111827',
    },
    previewContainer: {
      width: '100%',
      marginTop: 6,
    },
    previewImage: {
      width: '100%',
      aspectRatio: 0.74,
      borderRadius: 8,
      backgroundColor: '#F3F4F6',
    },
  });
