import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
  },
  headerTitle: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    marginLeft: 12,
    color: '#000',
  },
  recipientCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF',
    borderColor: '#737373',
    borderWidth: 0.4,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    marginTop: 16,
    marginHorizontal: 20,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2F80ED',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFF',
    fontFamily: 'Switzer-Medium',
  },
  recipientName: {
    fontFamily: 'Switzer-Medium',
    fontSize: 16,
  },
  recipientBank: {
    fontFamily: 'Switzer-Regular',
    fontSize: 14,
    marginTop: 4,
    color: '#000',
  },
  labelRp: {
    fontFamily: 'Switzer-Medium',
    fontSize: 20,
    marginBottom: 8,
    marginRight: 10
  },
  inputContainer: {
    flex: 1,
    height: 60,
    backgroundColor: '#FFF',
    borderWidth: 1.5,
    borderColor: '#E0E0E0',
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  inputContainerFocused: {
    borderColor: '#BFDBFE', 
    backgroundColor: '#FFF',
    shadowColor: '#2F80ED',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  label: {
    fontFamily: 'Switzer-Medium',
    fontSize: 14,
    marginBottom: 8,
  },
  inputAmountContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
    paddingVertical: 8,
    marginBottom: 16,
  },
  currency: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    marginRight: 8,
  },
  inputAmount: {
    fontFamily: 'Switzer-Medium',
    fontSize: 24,
    flex: 1,
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 24,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#F2F2F2',
    borderRadius: 25,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 21,
  },
  activeTab: {
    backgroundColor: '#2F80ED',
  },
  tabText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 12,
    color: '#666',
  },
  activeTabText: {
    color: '#FFF',
  },
  footer: {
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: '#F2F2F2',
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  totalText: {
    fontFamily: 'Switzer-Semibold',
    fontSize: 24,
    color: '#2F80ED',
  },
  confirmButton: {
    backgroundColor: '#2F80ED',
    paddingVertical: 10,
    borderRadius: 25,
    alignItems: 'center',
    marginTop: 12,
  },
  disabledButton: {
    backgroundColor: '#E0E0E0',
  },
  footerOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'transparent', 
  },
  footerContent: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32, 
    borderTopWidth: 1,
    borderTopColor: '#F2F2F2',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
    elevation: 10,
  },
});
