import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  scrollContent: {
    padding: 20,
  },
  vaCard: {
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginBottom: 32,
  },
  vaHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  bankLogoPlaceholder: {
    width: 40,
    height: 40,
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  bankInitial: {
    fontFamily: 'Switzer-Bold',
    fontSize: 12,
    color: '#1D4ED8',
  },
  bankNameText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 16,
    color: '#111827',
    marginLeft: 10
  },
  vaLabel: {
    fontFamily: 'Switzer-Regular',
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
  },
  vaNumberRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  vaNumberText: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    color: '#111827',
    letterSpacing: 0.5,
  },
  copyBadge: {
    flexDirection: 'row',
    backgroundColor: '#3475E8',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    alignItems: 'center',
  },
  copyText: {
    color: '#FFF',
    fontFamily: 'Switzer-Medium',
    fontSize: 14,
    marginLeft: 4
  },
  vaAmountText: {
    fontFamily: 'Switzer-Regular',
    fontSize: 22,
    color: '#111827',
  },
  guideTitle: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    color: '#111827',
    marginBottom: 16,
  },
  dropdownItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    marginBottom: 12,
  },
  dropdownText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 15,
    color: '#111827',
  },
  qrisContainer: {
    alignItems: 'center',
  },
  qrisLabel: {
    fontFamily: 'Switzer-Medium',
    fontSize: 14,
    color: '#6B7280',
  },
  qrisAmountWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
  },
  qrisCurrency: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    color: '#3B82F6',
    marginTop: 4,
    marginRight: 4,
  },
  qrisAmountText: {
    fontFamily: 'Switzer-Bold',
    fontSize: 48,
    color: '#3B82F6',
  },
  qrisTarget: {
    fontFamily: 'Switzer-Regular',
    fontSize: 15,
    color: '#111827',
    marginTop: 8,
    marginBottom: 32,
  },
  qrCard: {
    backgroundColor: '#FFF',
    padding: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    alignItems: 'center',
    width: '100%',
    marginBottom: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    paddingTop: 24
  },
  qrImagePlaceholder: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F3F4F6',
  },
  qrisLogoText: {
    fontFamily: 'Switzer-Bold',
    fontSize: 24,
    marginTop: 16,
    color: '#111827',
  },
  outlineButton: {
    flexDirection: 'row',
    width: '100%',
    height: 52,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 26,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
    marginBottom: 12,
  },
  outlineButtonText: {
    fontFamily: 'Switzer-Medium',
    fontSize: 15,
    color: '#111827',
  },
  qrisTargetBoldText: {
    fontFamily: 'Switzer-Bold',
    color: '#111827',
  },
  qrCodePlaceholderText: {
    fontFamily: 'Switzer-Bold',
    fontSize: 40,
    color: '#111827',
  },
  vaLabelWithMargin: {
    fontFamily: 'Switzer-Regular',
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 8,
    marginTop: 16,
  },
  vaAmountBoldText: {
    fontFamily: 'Switzer-Bold',
    color: '#111827',
  },
  vaShareButton: {
    marginTop: 16,
  },
  recipientInfo: {
    alignItems: 'center',
    marginBottom: 24,
  },
  recipientName: {
    fontFamily: 'Switzer-Medium',
    fontSize: 24,
    color: '#111827',
    marginBottom: 4,
  },
  recipientId: {
    fontFamily: 'Switzer-Regular',
    fontSize: 14,
    color: '#000',
  },
  inputAmountWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    marginBottom: 24,
  },
  inputCurrencyPrefix: {
    fontFamily: 'Switzer-Bold',
    fontSize: 18,
    color: '#111827',
    marginRight: 12,
  },
  amountText: {
    flex: 1,
    fontSize: 40,
    fontFamily: 'Switzer-Medium',
    color: '#0A0A0A',
  },
  amountInputPlaceholder: {
    fontSize: 14,
  },
  amountInputActive: {
    fontSize: 24,
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 20, 
    paddingTop: 16
  },
});
